# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Strategy2MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 776)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QWidget(self.centralwidget)
        self.header.setMinimumSize(QtCore.QSize(0, 80))
        self.header.setMaximumSize(QtCore.QSize(16777215, 80))
        self.header.setStyleSheet("")
        self.header.setObjectName("header")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.header)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.header)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.txtNextOption = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtNextOption.setFont(font)
        self.txtNextOption.setStyleSheet("color: rgb(255, 0, 0);")
        self.txtNextOption.setObjectName("txtNextOption")
        self.horizontalLayout.addWidget(self.txtNextOption)
        self.label_9 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.txtTodaySurplus = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtTodaySurplus.setFont(font)
        self.txtTodaySurplus.setStyleSheet("color: rgb(255, 0, 0);")
        self.txtTodaySurplus.setObjectName("txtTodaySurplus")
        self.horizontalLayout.addWidget(self.txtTodaySurplus)
        self.label_11 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.txtNextOpenTime = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtNextOpenTime.setFont(font)
        self.txtNextOpenTime.setStyleSheet("color: rgb(255, 0, 0);")
        self.txtNextOpenTime.setObjectName("txtNextOpenTime")
        self.horizontalLayout.addWidget(self.txtNextOpenTime)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.txtNextStopTime = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtNextStopTime.setFont(font)
        self.txtNextStopTime.setStyleSheet("color: rgb(255, 0, 0);")
        self.txtNextStopTime.setObjectName("txtNextStopTime")
        self.horizontalLayout.addWidget(self.txtNextStopTime)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.header)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 0, 0);")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.txtPrevAt = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtPrevAt.setFont(font)
        self.txtPrevAt.setStyleSheet("color: rgb(255, 0, 0);")
        self.txtPrevAt.setObjectName("txtPrevAt")
        self.horizontalLayout_2.addWidget(self.txtPrevAt)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.txtPrevLimit = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtPrevLimit.setFont(font)
        self.txtPrevLimit.setStyleSheet("color: rgb(255, 0, 0);")
        self.txtPrevLimit.setObjectName("txtPrevLimit")
        self.horizontalLayout_2.addWidget(self.txtPrevLimit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.txtLastOption = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtLastOption.setFont(font)
        self.txtLastOption.setStyleSheet("color: rgb(0, 85, 0);")
        self.txtLastOption.setObjectName("txtLastOption")
        self.horizontalLayout_2.addWidget(self.txtLastOption)
        self.label_13 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.txtN1 = QtWidgets.QLabel(self.widget_2)
        self.txtN1.setMinimumSize(QtCore.QSize(30, 30))
        self.txtN1.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtN1.setFont(font)
        self.txtN1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtN1.setObjectName("txtN1")
        self.horizontalLayout_2.addWidget(self.txtN1)
        self.txtN2 = QtWidgets.QLabel(self.widget_2)
        self.txtN2.setMinimumSize(QtCore.QSize(30, 30))
        self.txtN2.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtN2.setFont(font)
        self.txtN2.setAlignment(QtCore.Qt.AlignCenter)
        self.txtN2.setObjectName("txtN2")
        self.horizontalLayout_2.addWidget(self.txtN2)
        self.txtN3 = QtWidgets.QLabel(self.widget_2)
        self.txtN3.setMinimumSize(QtCore.QSize(30, 30))
        self.txtN3.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtN3.setFont(font)
        self.txtN3.setAlignment(QtCore.Qt.AlignCenter)
        self.txtN3.setObjectName("txtN3")
        self.horizontalLayout_2.addWidget(self.txtN3)
        self.txtN4 = QtWidgets.QLabel(self.widget_2)
        self.txtN4.setMinimumSize(QtCore.QSize(30, 30))
        self.txtN4.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtN4.setFont(font)
        self.txtN4.setAlignment(QtCore.Qt.AlignCenter)
        self.txtN4.setObjectName("txtN4")
        self.horizontalLayout_2.addWidget(self.txtN4)
        self.txtN5 = QtWidgets.QLabel(self.widget_2)
        self.txtN5.setMinimumSize(QtCore.QSize(30, 30))
        self.txtN5.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtN5.setFont(font)
        self.txtN5.setAlignment(QtCore.Qt.AlignCenter)
        self.txtN5.setObjectName("txtN5")
        self.horizontalLayout_2.addWidget(self.txtN5)
        self.txtN6 = QtWidgets.QLabel(self.widget_2)
        self.txtN6.setMinimumSize(QtCore.QSize(30, 30))
        self.txtN6.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtN6.setFont(font)
        self.txtN6.setAlignment(QtCore.Qt.AlignCenter)
        self.txtN6.setObjectName("txtN6")
        self.horizontalLayout_2.addWidget(self.txtN6)
        self.txtN7 = QtWidgets.QLabel(self.widget_2)
        self.txtN7.setMinimumSize(QtCore.QSize(30, 30))
        self.txtN7.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtN7.setFont(font)
        self.txtN7.setAlignment(QtCore.Qt.AlignCenter)
        self.txtN7.setObjectName("txtN7")
        self.horizontalLayout_2.addWidget(self.txtN7)
        self.txtN8 = QtWidgets.QLabel(self.widget_2)
        self.txtN8.setMinimumSize(QtCore.QSize(30, 30))
        self.txtN8.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtN8.setFont(font)
        self.txtN8.setAlignment(QtCore.Qt.AlignCenter)
        self.txtN8.setObjectName("txtN8")
        self.horizontalLayout_2.addWidget(self.txtN8)
        self.txtN9 = QtWidgets.QLabel(self.widget_2)
        self.txtN9.setMinimumSize(QtCore.QSize(30, 30))
        self.txtN9.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtN9.setFont(font)
        self.txtN9.setAlignment(QtCore.Qt.AlignCenter)
        self.txtN9.setObjectName("txtN9")
        self.horizontalLayout_2.addWidget(self.txtN9)
        self.txtN10 = QtWidgets.QLabel(self.widget_2)
        self.txtN10.setMinimumSize(QtCore.QSize(30, 30))
        self.txtN10.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtN10.setFont(font)
        self.txtN10.setAlignment(QtCore.Qt.AlignCenter)
        self.txtN10.setObjectName("txtN10")
        self.horizontalLayout_2.addWidget(self.txtN10)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.header)
        self.body = QtWidgets.QWidget(self.centralwidget)
        self.body.setMinimumSize(QtCore.QSize(1000, 650))
        self.body.setStyleSheet("")
        self.body.setObjectName("body")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.body)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.body)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(480, 16777215))
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 36))
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 36))
        self.widget_5.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.txtTips = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtTips.setFont(font)
        self.txtTips.setObjectName("txtTips")
        self.horizontalLayout_4.addWidget(self.txtTips)
        self.verticalLayout_3.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_3)
        self.widget_6.setStyleSheet("")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableTips = QtWidgets.QTableWidget(self.widget_6)
        self.tableTips.setMinimumSize(QtCore.QSize(0, 0))
        self.tableTips.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableTips.setFont(font)
        self.tableTips.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableTips.setDragDropOverwriteMode(False)
        self.tableTips.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableTips.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableTips.setObjectName("tableTips")
        self.tableTips.setColumnCount(8)
        self.tableTips.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableTips.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableTips.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableTips.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableTips.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableTips.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableTips.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableTips.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableTips.setHorizontalHeaderItem(7, item)
        self.tableTips.horizontalHeader().setDefaultSectionSize(60)
        self.tableTips.verticalHeader().setDefaultSectionSize(36)
        self.tableTips.verticalHeader().setMinimumSectionSize(36)
        self.verticalLayout_5.addWidget(self.tableTips)
        self.verticalLayout_3.addWidget(self.widget_6)
        self.horizontalLayout_3.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.body)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableTodayRecords = QtWidgets.QTableView(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableTodayRecords.setFont(font)
        self.tableTodayRecords.setToolTip("")
        self.tableTodayRecords.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableTodayRecords.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableTodayRecords.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableTodayRecords.setObjectName("tableTodayRecords")
        self.tableTodayRecords.horizontalHeader().setDefaultSectionSize(40)
        self.tableTodayRecords.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.tableTodayRecords)
        self.horizontalLayout_3.addWidget(self.widget_4)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addWidget(self.body)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPasswd = QtWidgets.QAction(MainWindow)
        self.actionPasswd.setObjectName("actionPasswd")
        self.actionOpenStrategyAdd = QtWidgets.QAction(MainWindow)
        self.actionOpenStrategyAdd.setObjectName("actionOpenStrategyAdd")
        self.actionStrategyList = QtWidgets.QAction(MainWindow)
        self.actionStrategyList.setObjectName("actionStrategyList")
        self.actionOpenPasswd = QtWidgets.QAction(MainWindow)
        self.actionOpenPasswd.setObjectName("actionOpenPasswd")
        self.actionOpenStaffsDialog = QtWidgets.QAction(MainWindow)
        self.actionOpenStaffsDialog.setObjectName("actionOpenStaffsDialog")
        self.actionOpenAccountDialog = QtWidgets.QAction(MainWindow)
        self.actionOpenAccountDialog.setObjectName("actionOpenAccountDialog")
        self.actionOpenWebsiteDialog = QtWidgets.QAction(MainWindow)
        self.actionOpenWebsiteDialog.setObjectName("actionOpenWebsiteDialog")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "策略2：日内已开最小次数追击法-幸运飞艇"))
        self.label_7.setText(_translate("MainWindow", "即将开："))
        self.txtNextOption.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "期，今日剩余："))
        self.txtTodaySurplus.setText(_translate("MainWindow", "120"))
        self.label_11.setText(_translate("MainWindow", "期"))
        self.label_3.setText(_translate("MainWindow", "开奖时间："))
        self.txtNextOpenTime.setText(_translate("MainWindow", "00:00:00"))
        self.label_5.setText(_translate("MainWindow", "停止下注："))
        self.txtNextStopTime.setText(_translate("MainWindow", "00:00:00"))
        self.label.setText(_translate("MainWindow", "目标期数："))
        self.txtPrevAt.setText(_translate("MainWindow", "161"))
        self.label_2.setText(_translate("MainWindow", "，最小次数："))
        self.txtPrevLimit.setText(_translate("MainWindow", "9"))
        self.txtLastOption.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "期开奖号码"))
        self.txtN1.setText(_translate("MainWindow", "?"))
        self.txtN2.setText(_translate("MainWindow", "?"))
        self.txtN3.setText(_translate("MainWindow", "?"))
        self.txtN4.setText(_translate("MainWindow", "?"))
        self.txtN5.setText(_translate("MainWindow", "?"))
        self.txtN6.setText(_translate("MainWindow", "?"))
        self.txtN7.setText(_translate("MainWindow", "?"))
        self.txtN8.setText(_translate("MainWindow", "?"))
        self.txtN9.setText(_translate("MainWindow", "?"))
        self.txtN10.setText(_translate("MainWindow", "?"))
        self.txtTips.setText(_translate("MainWindow", "正在加载行情...分析中..."))
        item = self.tableTips.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "赛道"))
        item = self.tableTips.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "号码"))
        item = self.tableTips.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "次数"))
        item = self.tableTips.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "状态"))
        item = self.tableTips.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "全场胜"))
        item = self.tableTips.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "全场负"))
        item = self.tableTips.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "下半场胜"))
        item = self.tableTips.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "下半场负"))


